/* Hospital Analytics - 04 Department Analysis */
USE HospitalAnalytics;
GO
SELECT department,COUNT(*) total_admissions FROM dbo.admissions GROUP BY department ORDER BY total_admissions DESC;
SELECT a.department,COUNT(DISTINCT a.admission_id) total_admissions,SUM(b.total_amount) total_revenue,AVG(b.total_amount) avg_bill_amount,SUM(b.total_amount)/NULLIF(COUNT(DISTINCT a.admission_id),0) revenue_per_admission FROM dbo.admissions a JOIN dbo.billing b ON a.admission_id=b.admission_id GROUP BY a.department ORDER BY total_revenue DESC;
SELECT department,COUNT(*) total_admissions,SUM(CASE WHEN discharge_status='Recovered' THEN 1 ELSE 0 END) recovered_cases,ROUND(100.0*SUM(CASE WHEN discharge_status='Recovered' THEN 1 ELSE 0 END)/COUNT(*),2) recovery_rate_pct FROM dbo.admissions GROUP BY department ORDER BY recovery_rate_pct DESC;
SELECT department,COUNT(*) total_admissions,SUM(CASE WHEN discharge_status='Deceased' THEN 1 ELSE 0 END) deceased_cases,ROUND(100.0*SUM(CASE WHEN discharge_status='Deceased' THEN 1 ELSE 0 END)/COUNT(*),2) mortality_rate_pct FROM dbo.admissions GROUP BY department ORDER BY mortality_rate_pct DESC;
SELECT department,COUNT(*) total_admissions,ROUND(AVG(CAST(DATEDIFF(DAY,admission_date,discharge_date) AS DECIMAL(10,2))),2) avg_length_of_stay_days FROM dbo.admissions GROUP BY department ORDER BY avg_length_of_stay_days DESC;
SELECT department,COUNT(*) total_appointments,ROUND(AVG(wait_time_minutes),2) avg_wait_time_minutes,SUM(CASE WHEN appointment_status='Completed' THEN 1 ELSE 0 END) completed_appointments FROM dbo.appointments GROUP BY department ORDER BY avg_wait_time_minutes DESC;
GO
WITH da AS(SELECT department,COUNT(*) total_admissions,SUM(CASE WHEN discharge_status='Recovered' THEN 1 ELSE 0 END) recovered_cases,SUM(CASE WHEN discharge_status='Deceased' THEN 1 ELSE 0 END) deceased_cases,AVG(CAST(DATEDIFF(DAY,admission_date,discharge_date) AS DECIMAL(10,2))) avg_los FROM dbo.admissions GROUP BY department),dr AS(SELECT a.department,SUM(b.total_amount) total_revenue FROM dbo.admissions a JOIN dbo.billing b ON a.admission_id=b.admission_id GROUP BY a.department) SELECT da.department,da.total_admissions,dr.total_revenue,ROUND(100.0*da.recovered_cases/da.total_admissions,2) recovery_rate_pct,ROUND(100.0*da.deceased_cases/da.total_admissions,2) mortality_rate_pct,ROUND(da.avg_los,2) avg_length_of_stay_days FROM da JOIN dr ON da.department=dr.department ORDER BY dr.total_revenue DESC;
WITH r AS(SELECT a.department,SUM(b.total_amount) total_revenue FROM dbo.admissions a JOIN dbo.billing b ON a.admission_id=b.admission_id GROUP BY a.department) SELECT department,total_revenue,DENSE_RANK() OVER(ORDER BY total_revenue DESC) revenue_rank FROM r ORDER BY revenue_rank;
