/* Hospital Analytics - 06 Advanced Analysis */
USE HospitalAnalytics;
GO
WITH m AS(SELECT DATEFROMPARTS(YEAR(a.admission_date),MONTH(a.admission_date),1) month_start,SUM(b.total_amount) total_revenue FROM dbo.admissions a JOIN dbo.billing b ON a.admission_id=b.admission_id GROUP BY DATEFROMPARTS(YEAR(a.admission_date),MONTH(a.admission_date),1)) SELECT month_start,total_revenue,LAG(total_revenue) OVER(ORDER BY month_start) previous_month_revenue,ROUND(100.0*(total_revenue-LAG(total_revenue) OVER(ORDER BY month_start))/NULLIF(LAG(total_revenue) OVER(ORDER BY month_start),0),2) mom_revenue_change_pct FROM m ORDER BY month_start;
WITH r AS(SELECT a.department,SUM(b.total_amount) total_revenue FROM dbo.admissions a JOIN dbo.billing b ON a.admission_id=b.admission_id GROUP BY a.department) SELECT department,total_revenue,ROUND(100.0*total_revenue/SUM(total_revenue) OVER(),2) revenue_share_pct,DENSE_RANK() OVER(ORDER BY total_revenue DESC) revenue_rank FROM r ORDER BY revenue_rank;
SELECT a.department,COUNT(DISTINCT a.admission_id) total_admissions,SUM(b.total_amount) total_revenue,ROUND(SUM(b.total_amount)/NULLIF(COUNT(DISTINCT a.admission_id),0),2) revenue_per_admission FROM dbo.admissions a JOIN dbo.billing b ON a.admission_id=b.admission_id GROUP BY a.department ORDER BY revenue_per_admission DESC;
WITH p AS(SELECT patient_id,COUNT(*) admission_count FROM dbo.admissions GROUP BY patient_id) SELECT COUNT(*) patients_with_2plus_admissions FROM p WHERE admission_count>=2;
WITH r AS(SELECT a.department,SUM(b.total_amount) total_revenue FROM dbo.admissions a JOIN dbo.billing b ON a.admission_id=b.admission_id GROUP BY a.department),x AS(SELECT department,total_revenue,DENSE_RANK() OVER(ORDER BY total_revenue DESC) revenue_rank FROM r) SELECT * FROM x WHERE revenue_rank<=3 ORDER BY revenue_rank;
SELECT department,COUNT(*) total_admissions,SUM(CASE WHEN discharge_status='Deceased' THEN 1 ELSE 0 END) deceased_cases,ROUND(100.0*SUM(CASE WHEN discharge_status='Deceased' THEN 1 ELSE 0 END)/COUNT(*),2) mortality_rate_pct FROM dbo.admissions GROUP BY department HAVING COUNT(*)>=100 ORDER BY mortality_rate_pct DESC;
SELECT COUNT(*) total_appointments,SUM(CASE WHEN appointment_status='Completed' THEN 1 ELSE 0 END) completed,SUM(CASE WHEN appointment_status='Cancelled' THEN 1 ELSE 0 END) cancelled,SUM(CASE WHEN appointment_status='Rescheduled' THEN 1 ELSE 0 END) rescheduled,SUM(CASE WHEN appointment_status='No-Show' THEN 1 ELSE 0 END) no_show,ROUND(100.0*SUM(CASE WHEN appointment_status='Completed' THEN 1 ELSE 0 END)/COUNT(*),2) completion_rate_pct FROM dbo.appointments;
SELECT status,COUNT(*) total_beds,ROUND(100.0*COUNT(*)/SUM(COUNT(*)) OVER(),2) bed_share_pct FROM dbo.beds GROUP BY status ORDER BY total_beds DESC;
SELECT treatment_type,COUNT(*) total_treatments,SUM(treatment_cost) total_treatment_cost,AVG(treatment_cost) avg_treatment_cost FROM dbo.treatments GROUP BY treatment_type ORDER BY total_treatment_cost DESC;
SELECT TOP 15 diagnosis,COUNT(*) total_treatments,SUM(treatment_cost) total_treatment_cost,AVG(treatment_cost) avg_treatment_cost FROM dbo.treatments GROUP BY diagnosis ORDER BY total_treatment_cost DESC;
